USE lumina;
/*  -----   INSERTAR MARCAS DE ARMAZONES    -----   */
CALL categoriesManager(null, 'Advance episode','Marca',1);
CALL categoriesManager(null, 'Aidefu','Marca',1);
CALL categoriesManager(null, 'Alena & Class','Marca',1);
CALL categoriesManager(null, 'Ansi','Marca',1);
CALL categoriesManager(null, 'Armani exchange','Marca',1);
CALL categoriesManager(null, 'Axe Italy','Marca',1);
CALL categoriesManager(null, 'Axel Eye Wear','Marca',1);
CALL categoriesManager(null, 'Back to Back','Marca',1);
CALL categoriesManager(null, 'Blanc And Noir','Marca',1);
CALL categoriesManager(null, 'Body Glove','Marca',1);
CALL categoriesManager(null, 'Caffdy','Marca',1);
CALL categoriesManager(null, 'Carnaval','Marca',1);
CALL categoriesManager(null, 'Cierzo','Marca',1);
CALL categoriesManager(null, 'Clóe','Marca',1);
CALL categoriesManager(null, 'C-mark','Marca',1);
CALL categoriesManager(null, 'Corine Mc Cormack','Marca',1);
CALL categoriesManager(null, 'Children','Marca',1);
CALL categoriesManager(null, 'Discovery','Marca',1);
CALL categoriesManager(null, 'Disney','Marca',1);
CALL categoriesManager(null, 'Dkny','Marca',1);
CALL categoriesManager(null, 'Eco-iris','Marca',1);
CALL categoriesManager(null, 'Fennica','Marca',1);
CALL categoriesManager(null, 'Holz','Marca',1);
CALL categoriesManager(null, 'Italy Design','Marca',1);
CALL categoriesManager(null, 'Karolyna','Marca',1);
CALL categoriesManager(null, 'Kipling','Marca',1);
CALL categoriesManager(null, 'L.a. express','Marca',1);
CALL categoriesManager(null, 'Lantis','Marca',1);
CALL categoriesManager(null, 'Levis','Marca',1);
CALL categoriesManager(null, 'Mazzimo Rozzi','Marca',1);
CALL categoriesManager(null, 'Michael Kors','Marca',1);
CALL categoriesManager(null, 'Mosson','Marca',1);
CALL categoriesManager(null, 'Nano vista','Marca',1);
CALL categoriesManager(null, 'Nikitana','Marca',1);
CALL categoriesManager(null, 'Oakley','Marca',1);
CALL categoriesManager(null, 'Owen','Marca',1);
CALL categoriesManager(null, 'Panlees','Marca',1);
CALL categoriesManager(null, 'Polariz','Marca',1);
CALL categoriesManager(null, 'Puppy Eyes','Marca',1);
CALL categoriesManager(null, 'Ralph Lauren','Marca',1);
CALL categoriesManager(null, 'Ray Ban','Marca',1);
CALL categoriesManager(null, 'Reebok','Marca',1);
CALL categoriesManager(null, 'Rote Sonne','Marca',1);
CALL categoriesManager(null, 'Senbird','Marca',1);
CALL categoriesManager(null, 'Solar','Marca',1);
CALL categoriesManager(null, 'Susan','Marca',1);
CALL categoriesManager(null, 'Swapit','Marca',1);
CALL categoriesManager(null, 'Tg','Marca',1);
CALL categoriesManager(null, 'Twister','Marca',1);
CALL categoriesManager(null, 'Twister improve','Marca',1);
CALL categoriesManager(null, 'V-flex next','Marca',1);
CALL categoriesManager(null, 'Videri','Marca',1);
CALL categoriesManager(null, 'Visual','Marca',1);
CALL categoriesManager(null, 'Vogue','Marca',1);
CALL categoriesManager(null, 'X-dogydog','Marca',1);